#!/usr/bin/env python3
"""Bundle index.json + checkpoint_*.json into viewer/data.js (a global constant).

The viewer loads data.js with a plain <script> tag, so it works over file:// too.
Usage: python bundle_data.py <json_dir> [--out viewer/data.js]
"""
import argparse, json, pathlib


def bundle(json_dir, out_path):
    json_dir = pathlib.Path(json_dir)
    index = json.loads((json_dir / "index.json").read_text())
    checkpoints = [json.loads((json_dir / c["file"]).read_text()) for c in index["checkpoints"]]
    payload = json.dumps({"index": index, "checkpoints": checkpoints}, separators=(",", ":"))
    out_path = pathlib.Path(out_path)
    out_path.write_text("// Generated by bundle_data.py from %s. Do not edit.\nconst DEMO_DATA = %s;\n"
                        % (json_dir.name, payload))
    print(f"wrote {out_path} ({out_path.stat().st_size / 1e6:.1f} MB, {len(checkpoints)} checkpoints)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("json_dir")
    ap.add_argument("--out", default=str(pathlib.Path(__file__).parent / "viewer" / "data.js"))
    a = ap.parse_args()
    bundle(a.json_dir, a.out)
