#!/usr/bin/env python3
"""Export SARL checkpoints as weights the viewer can run in the browser.

The viewer needs this to let a visitor move the goal: the robot then has to decide for itself,
instead of replaying a recorded trajectory. Values are stored as float16 to keep the file small;
that is far below the precision the decisions need.

    python training/export_weights.py training/runs/sarl_humans/checkpoints

Writes viewer/weights.js: const SARL_WEIGHTS = {layers, gamma, checkpoints: [{training_steps, data}]}.
"""
from __future__ import annotations

import argparse
import base64
import json
import re
from pathlib import Path

import numpy as np
import torch

HERE = Path(__file__).resolve().parent

# Order matters: the viewer reads the buffer back in this order.
LAYERS = ["mlp1.0", "mlp1.2", "mlp2.0", "mlp2.2", "attention.0", "attention.2", "attention.4",
          "mlp3.0", "mlp3.2", "mlp3.4", "mlp3.6"]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("checkpoint_dir", type=Path)
    ap.add_argument("--out", type=Path, default=HERE.parent / "viewer" / "weights.js")
    ap.add_argument("--gamma", type=float, default=0.9, help="discount used when scoring moves (policy.config)")
    a = ap.parse_args()

    checkpoints = sorted(a.checkpoint_dir.glob("*.pt"), key=lambda p: int(re.search(r"(\d+)", p.stem).group(1)))
    if not checkpoints:
        raise SystemExit(f"no checkpoints in {a.checkpoint_dir}")

    shapes, entries = None, []
    for path in checkpoints:
        sd = torch.load(path, map_location="cpu", weights_only=True)
        flat = []
        for name in LAYERS:
            flat.append(sd[f"{name}.weight"].numpy().astype(np.float16).ravel())
            flat.append(sd[f"{name}.bias"].numpy().astype(np.float16).ravel())
        if shapes is None:
            shapes = [[name, list(sd[f"{name}.weight"].shape)] for name in LAYERS]
        buffer = np.concatenate(flat).tobytes()
        entries.append({"training_steps": int(re.search(r"(\d+)", path.stem).group(1)),
                        "data": base64.b64encode(buffer).decode()})

    payload = {"layers": shapes, "gamma": a.gamma, "checkpoints": entries}
    a.out.write_text("// Generated by training/export_weights.py. Do not edit.\n"
                     "const SARL_WEIGHTS = %s;\n" % json.dumps(payload, separators=(",", ":")))
    print(f"wrote {a.out} ({a.out.stat().st_size / 1e6:.1f} MB, {len(entries)} checkpoints)")


if __name__ == "__main__":
    main()
